services:
  db:
    image: postgres:16
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file: .env
    depends_on: [db]
    ports:
      - "8000:8000"

  scraper:
    build: ./docker/scraper
    env_file: .env
    depends_on: [api]

volumes:
  pgdata: